name: textgen

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  textgen.write:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python pdfgen/convert.py
