# name: Convert YAML into LaTeX then compile into PDF.

# on:
#   push:
#     branches:
#       - main  # Set a branch to deploy
#   pull_request:

# jobs:
#   textgen:
#     permissions: write-all
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.9'
#           cache: 'pip' # caching pip dependencies
#       - name: Delete existing tex file
#         run:  |
#           rm ./pdfgen/content.tex
#       - name: Make sure file was deleted
#         run:  |
#           ls pdfgen
#       - name: Create new tex file
#         run:  |
#           pip install -r requirements.txt
#           python pdfgen/convert.py
#       - name: List created files
#         run:  |
#           ls pdfgen
#       - name: Setup git config
#         run: |
#           git config user.name "GitHub Actions Bot"
#           git config user.email "<>"
#       - name: Commit files
#         run: |
#           git add pdfgen/content.tex
#           git commit -m "Add changes" --no-verify
#           git push origin main --force
#       # - name: Push changes
#       #   uses: ad-m/github-push-action@master
#       #   with:
#       #     github_token: ${{ secrets.GITHUB_TOKEN }}
#       #     branch: ${{ github.ref }}

#   build_latex:
#     runs-on: ubuntu-latest
#     needs: textgen
#     steps:
#       - name: Set up Git repository
#         uses: actions/checkout@v3
#       - name: Delete PDF
#         run: |
#           rm pdfgen/cv.pdf
#       - name: Compile LaTeX document
#         uses: xu-cheng/latex-action@v2
#         with:
#           root_file: pdfgen/content.tex
#       - name: list files
#         run: |
#           ls .
#           echo "-------"
#           ls pdfgen/
#       - name: Copy file to proper directory
#         run: |
#           cp content.pdf pdfgen/cv.pdf
#       - name: setup git config
#         run: |
#           git config user.name "GitHub Actions Bot"
#           git config user.email "<>"
#       - name: commit
#         run: |
#           git add pdfgen/cv.pdf
#           git commit -m "Auto-generated PDF" --no-verify
#           git push origin main --force
